CREATE TABLE [dbo].[businessunit](
	[versionnumber] [bigint] NULL,
	[address2_line2] [nvarchar](250) NULL,
	[createdon] [datetime] NULL,
	[address1_longitude] [float] NULL,
	[modifiedonbehalfbyyominame] [nvarchar](4000) NULL,
	[address1_county] [nvarchar](50) NULL,
	[address1_addressid] [uniqueidentifier] NULL,
	[address2_telephone1] [nvarchar](50) NULL,
	[address2_telephone2] [nvarchar](50) NULL,
	[address2_telephone3] [nvarchar](50) NULL,
	[modifiedbyyominame] [nvarchar](4000) NULL,
	[parentbusinessunitid] [uniqueidentifier] NULL,
	[parentbusinessunitidname] [nvarchar](4000) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[address2_addressid] [uniqueidentifier] NULL,
	[inheritancemask] [int] NULL,
	[ftpsiteurl] [nvarchar](200) NULL,
	[overriddencreatedon] [datetime] NULL,
	[address2_name] [nvarchar](100) NULL,
	[websiteurl] [nvarchar](200) NULL,
	[address2_country] [nvarchar](80) NULL,
	[createdonbehalfbyyominame] [nvarchar](4000) NULL,
	[address1_line1] [nvarchar](250) NULL,
	[exchangerate] [decimal](22, 10) NULL,
	[address1_stateorprovince] [nvarchar](50) NULL,
	[address2_postalcode] [nvarchar](20) NULL,
	[address2_county] [nvarchar](50) NULL,
	[address1_country] [nvarchar](80) NULL,
	[address1_postalcode] [nvarchar](20) NULL,
	[address1_fax] [nvarchar](50) NULL,
	[utcoffset] [int] NULL,
	[address1_line3] [nvarchar](250) NULL,
	[address1_utcoffset] [int] NULL,
	[workflowsuspended] [tinyint] NULL,
	[emailaddress] [nvarchar](100) NULL,
	[address2_utcoffset] [int] NULL,
	[address2_line1] [nvarchar](250) NULL,
	[createdonbehalfbyname] [nvarchar](4000) NULL,
	[address2_upszone] [nvarchar](4) NULL,
	[address2_postofficebox] [nvarchar](20) NULL,
	[address1_city] [nvarchar](80) NULL,
	[tickersymbol] [nvarchar](10) NULL,
	[picture] [nvarchar](max) NULL,
	[address1_telephone1] [nvarchar](50) NULL,
	[address1_telephone2] [nvarchar](50) NULL,
	[address1_telephone3] [nvarchar](50) NULL,
	[modifiedon] [datetime] NULL,
	[usergroupid] [uniqueidentifier] NULL,
	[address2_stateorprovince] [nvarchar](50) NULL,
	[description] [nvarchar](max) NULL,
	[address2_shippingmethodcode] [int] NULL,
	[address2_shippingmethodcode_displayname] [nvarchar](255) NULL,
	[address1_name] [nvarchar](100) NULL,
	[createdbyname] [nvarchar](4000) NULL,
	[disabledreason] [nvarchar](500) NULL,
	[isdisabled] [tinyint] NULL,
	[modifiedonbehalfbyname] [nvarchar](4000) NULL,
	[address1_shippingmethodcode] [int] NULL,
	[address1_shippingmethodcode_displayname] [nvarchar](255) NULL,
	[address2_addresstypecode] [int] NULL,
	[address2_addresstypecode_displayname] [nvarchar](255) NULL,
	[address1_line2] [nvarchar](250) NULL,
	[address2_longitude] [float] NULL,
	[address2_city] [nvarchar](80) NULL,
	[calendarid] [uniqueidentifier] NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[createdby] [uniqueidentifier] NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[address2_fax] [nvarchar](50) NULL,
	[stockexchange] [nvarchar](20) NULL,
	[createdbyyominame] [nvarchar](4000) NULL,
	[transactioncurrencyidname] [nvarchar](4000) NULL,
	[creditlimit] [float] NULL,
	[address1_addresstypecode] [int] NULL,
	[address1_addresstypecode_displayname] [nvarchar](255) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[divisionname] [nvarchar](100) NULL,
	[address1_latitude] [float] NULL,
	[name] [nvarchar](160) NULL,
	[address1_upszone] [nvarchar](4) NULL,
	[modifiedbyname] [nvarchar](4000) NULL,
	[organizationid] [uniqueidentifier] NULL,
	[address2_line3] [nvarchar](250) NULL,
	[fileasname] [nvarchar](100) NULL,
	[address2_latitude] [float] NULL,
	[organizationidname] [nvarchar](4000) NULL,
	[costcenter] [nvarchar](100) NULL,
	[businessunitid] [uniqueidentifier] NULL,
	[importsequencenumber] [int] NULL,
	[address1_postofficebox] [nvarchar](20) NULL,
	[SCRIBE_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SCRIBE_CREATEDON] [datetime] NOT NULL,
	[SCRIBE_MODIFIEDON] [datetime] NOT NULL,
	[SCRIBE_DELETEDON] [datetime] NULL,
 CONSTRAINT [PK_businessunit] PRIMARY KEY CLUSTERED 
(
	[SCRIBE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

