CREATE TABLE [dbo].[lead] (
    [contactid]                               UNIQUEIDENTIFIER NULL,
    [emailaddress3]                           NVARCHAR (100)   NULL,
    [emailaddress2]                           NVARCHAR (100)   NULL,
    [emailaddress1]                           NVARCHAR (100)   NULL,
    [address1_city]                           NVARCHAR (80)    NULL,
    [budgetamount_base]                       DECIMAL (19, 4)  NULL,
    [address1_line1]                          NVARCHAR (250)   NULL,
    [budgetstatus]                            INT              NULL,
    [budgetstatus_displayname]                NVARCHAR (255)   NULL,
    [modifiedon]                              DATETIME         NULL,
    [address1_longitude]                      FLOAT (53)       NULL,
    [overriddencreatedon]                     DATETIME         NULL,
    [websiteurl]                              NVARCHAR (200)   NULL,
    [yomifirstname]                           NVARCHAR (150)   NULL,
    [yomifullname]                            NVARCHAR (450)   NULL,
    [accountid]                               UNIQUEIDENTIFIER NULL,
    [address1_addresstypecode]                INT              NULL,
    [address1_addresstypecode_displayname]    NVARCHAR (255)   NULL,
    [entityimage_timestamp]                   BIGINT           NULL,
    [contactidname]                           NVARCHAR (4000)  NULL,
    [telephone3]                              NVARCHAR (50)    NULL,
    [confirminterest]                         TINYINT          NULL,
    [address2_county]                         NVARCHAR (50)    NULL,
    [transactioncurrencyidname]               NVARCHAR (4000)  NULL,
    [address1_shippingmethodcode]             INT              NULL,
    [address1_shippingmethodcode_displayname] NVARCHAR (255)   NULL,
    [estimatedamount]                         DECIMAL (15, 2)  NULL,
    [accountidname]                           NVARCHAR (4000)  NULL,
    [relatedobjectidname]                     NVARCHAR (4000)  NULL,
    [campaignidname]                          NVARCHAR (4000)  NULL,
    [pager]                                   NVARCHAR (20)    NULL,
    [masterleadidyominame]                    NVARCHAR (4000)  NULL,
    [owningbusinessunit]                      UNIQUEIDENTIFIER NULL,
    [address2_stateorprovince]                NVARCHAR (50)    NULL,
    [mobilephone]                             NVARCHAR (20)    NULL,
    [address2_country]                        NVARCHAR (80)    NULL,
    [address2_line2]                          NVARCHAR (250)   NULL,
    [qualifyingopportunityid]                 UNIQUEIDENTIFIER NULL,
    [relatedobjectid]                         UNIQUEIDENTIFIER NULL,
    [owneridyominame]                         NVARCHAR (4000)  NULL,
    [parentcontactid]                         UNIQUEIDENTIFIER NULL,
    [statuscode]                              INT              NULL,
    [statuscode_displayname]                  NVARCHAR (255)   NULL,
    [estimatedclosedate]                      DATETIME         NULL,
    [parentaccountidname]                     NVARCHAR (4000)  NULL,
    [address1_utcoffset]                      INT              NULL,
    [numberofemployees]                       INT              NULL,
    [initialcommunication]                    INT              NULL,
    [initialcommunication_displayname]        NVARCHAR (255)   NULL,
    [parentaccountidyominame]                 NVARCHAR (4000)  NULL,
    [exchangerate]                            DECIMAL (22, 10) NULL,
    [isprivate]                               TINYINT          NULL,
    [companyname]                             NVARCHAR (100)   NULL,
    [parentaccountid]                         UNIQUEIDENTIFIER NULL,
    [address2_city]                           NVARCHAR (80)    NULL,
    [address2_shippingmethodcode]             INT              NULL,
    [address2_shippingmethodcode_displayname] NVARCHAR (255)   NULL,
    [new_leadproduct]                         INT              NULL,
    [new_leadproduct_displayname]             NVARCHAR (255)   NULL,
    [address2_latitude]                       FLOAT (53)       NULL,
    [createdon]                               DATETIME         NULL,
    [donotbulkemail]                          TINYINT          NULL,
    [createdbyyominame]                       NVARCHAR (4000)  NULL,
    [donotfax]                                TINYINT          NULL,
    [address1_composite]                      NVARCHAR (MAX)   NULL,
    [firstname]                               NVARCHAR (50)    NULL,
    [createdonbehalfby]                       UNIQUEIDENTIFIER NULL,
    [donotpostalmail]                         TINYINT          NULL,
    [salesstage]                              INT              NULL,
    [salesstage_displayname]                  NVARCHAR (255)   NULL,
    [evaluatefit]                             TINYINT          NULL,
    [address1_country]                        NVARCHAR (80)    NULL,
    [qualificationcomments]                   NVARCHAR (MAX)   NULL,
    [address2_postalcode]                     NVARCHAR (20)    NULL,
    [lastusedincampaign]                      DATETIME         NULL,
    [originatingcaseid]                       UNIQUEIDENTIFIER NULL,
    [entityimage_url]                         NVARCHAR (4000)  NULL,
    [address2_line3]                          NVARCHAR (250)   NULL,
    [description]                             NVARCHAR (MAX)   NULL,
    [modifiedby]                              UNIQUEIDENTIFIER NULL,
    [timezoneruleversionnumber]               INT              NULL,
    [address1_county]                         NVARCHAR (50)    NULL,
    [preferredcontactmethodcode]              INT              NULL,
    [preferredcontactmethodcode_displayname]  NVARCHAR (255)   NULL,
    [modifiedonbehalfby]                      UNIQUEIDENTIFIER NULL,
    [leadqualitycode]                         INT              NULL,
    [leadqualitycode_displayname]             NVARCHAR (255)   NULL,
    [subject]                                 NVARCHAR (300)   NULL,
    [address2_telephone2]                     NVARCHAR (50)    NULL,
    [isdc_contactability]                     INT              NULL,
    [isautocreate]                            TINYINT          NULL,
    [address2_postofficebox]                  NVARCHAR (20)    NULL,
    [address2_telephone1]                     NVARCHAR (50)    NULL,
    [yomilastname]                            NVARCHAR (150)   NULL,
    [address2_telephone3]                     NVARCHAR (50)    NULL,
    [address1_addressid]                      UNIQUEIDENTIFIER NULL,
    [traversedpath]                           NVARCHAR (1250)  NULL,
    [estimatedvalue]                          FLOAT (53)       NULL,
    [leadsourcecode]                          INT              NULL,
    [leadsourcecode_displayname]              NVARCHAR (255)   NULL,
    [owninguser]                              UNIQUEIDENTIFIER NULL,
    [industrycode]                            INT              NULL,
    [industrycode_displayname]                NVARCHAR (255)   NULL,
    [salesstagecode]                          INT              NULL,
    [salesstagecode_displayname]              NVARCHAR (255)   NULL,
    [address2_name]                           NVARCHAR (100)   NULL,
    [schedulefollowup_qualify]                DATETIME         NULL,
    [middlename]                              NVARCHAR (50)    NULL,
    [entityimageid]                           UNIQUEIDENTIFIER NULL,
    [parentcontactidyominame]                 NVARCHAR (4000)  NULL,
    [modifiedonbehalfbyname]                  NVARCHAR (4000)  NULL,
    [createdonbehalfbyyominame]               NVARCHAR (4000)  NULL,
    [address2_composite]                      NVARCHAR (MAX)   NULL,
    [customerid]                              UNIQUEIDENTIFIER NULL,
    [participatesinworkflow]                  TINYINT          NULL,
    [owningteam]                              UNIQUEIDENTIFIER NULL,
    [address1_stateorprovince]                NVARCHAR (50)    NULL,
    [address1_latitude]                       FLOAT (53)       NULL,
    [createdonbehalfbyname]                   NVARCHAR (4000)  NULL,
    [address1_line3]                          NVARCHAR (250)   NULL,
    [isdc_neuralscore]                        INT              NULL,
    [processid]                               UNIQUEIDENTIFIER NULL,
    [decisionmaker]                           TINYINT          NULL,
    [revenue]                                 DECIMAL (17, 2)  NULL,
    [jobtitle]                                NVARCHAR (100)   NULL,
    [transactioncurrencyid]                   UNIQUEIDENTIFIER NULL,
    [address1_telephone1]                     NVARCHAR (50)    NULL,
    [address1_telephone2]                     NVARCHAR (50)    NULL,
    [address1_telephone3]                     NVARCHAR (50)    NULL,
    [customeridyominame]                      NVARCHAR (4000)  NULL,
    [fax]                                     NVARCHAR (50)    NULL,
    [masterid]                                UNIQUEIDENTIFIER NULL,
    [yomimiddlename]                          NVARCHAR (150)   NULL,
    [masterleadidname]                        NVARCHAR (4000)  NULL,
    [ownerid]                                 UNIQUEIDENTIFIER NULL,
    [address2_utcoffset]                      INT              NULL,
    [address2_fax]                            NVARCHAR (50)    NULL,
    [revenue_base]                            DECIMAL (19, 4)  NULL,
    [merged]                                  TINYINT          NULL,
    [owneridtype]                             NVARCHAR (255)   NULL,
    [purchasetimeframe]                       INT              NULL,
    [purchasetimeframe_displayname]           NVARCHAR (255)   NULL,
    [budgetamount]                            DECIMAL (15, 2)  NULL,
    [address2_longitude]                      FLOAT (53)       NULL,
    [donotemail]                              TINYINT          NULL,
    [createdbyname]                           NVARCHAR (4000)  NULL,
    [donotphone]                              TINYINT          NULL,
    [modifiedbyyominame]                      NVARCHAR (4000)  NULL,
    [customeridtype]                          NVARCHAR (255)   NULL,
    [schedulefollowup_prospect]               DATETIME         NULL,
    [address1_line2]                          NVARCHAR (250)   NULL,
    [donotsendmm]                             TINYINT          NULL,
    [createdby]                               UNIQUEIDENTIFIER NULL,
    [address2_addresstypecode]                INT              NULL,
    [address2_addresstypecode_displayname]    NVARCHAR (255)   NULL,
    [address2_upszone]                        NVARCHAR (4)     NULL,
    [salutation]                              NVARCHAR (100)   NULL,
    [address1_postalcode]                     NVARCHAR (20)    NULL,
    [stageid]                                 UNIQUEIDENTIFIER NULL,
    [utcconversiontimezonecode]               INT              NULL,
    [leadid]                                  UNIQUEIDENTIFIER NULL,
    [campaignid]                              UNIQUEIDENTIFIER NULL,
    [qualifyingopportunityidname]             NVARCHAR (4000)  NULL,
    [address2_addressid]                      UNIQUEIDENTIFIER NULL,
    [customeridname]                          NVARCHAR (4000)  NULL,
    [importsequencenumber]                    INT              NULL,
    [telephone2]                              NVARCHAR (50)    NULL,
    [versionnumber]                           BIGINT           NULL,
    [telephone1]                              NVARCHAR (50)    NULL,
    [address1_name]                           NVARCHAR (100)   NULL,
    [address1_fax]                            NVARCHAR (50)    NULL,
    [contactidyominame]                       NVARCHAR (4000)  NULL,
    [yomicompanyname]                         NVARCHAR (100)   NULL,
    [originatingcaseidname]                   NVARCHAR (4000)  NULL,
    [parentcontactidname]                     NVARCHAR (4000)  NULL,
    [purchaseprocess]                         INT              NULL,
    [purchaseprocess_displayname]             NVARCHAR (255)   NULL,
    [modifiedbyname]                          NVARCHAR (4000)  NULL,
    [estimatedamount_base]                    DECIMAL (19, 4)  NULL,
    [owneridname]                             NVARCHAR (4000)  NULL,
    [address2_line1]                          NVARCHAR (250)   NULL,
    [address1_upszone]                        NVARCHAR (4)     NULL,
    [lastname]                                NVARCHAR (50)    NULL,
    [accountidyominame]                       NVARCHAR (4000)  NULL,
    [fullname]                                NVARCHAR (160)   NULL,
    [modifiedonbehalfbyyominame]              NVARCHAR (4000)  NULL,
    [prioritycode]                            INT              NULL,
    [prioritycode_displayname]                NVARCHAR (255)   NULL,
    [need]                                    INT              NULL,
    [need_displayname]                        NVARCHAR (255)   NULL,
    [address1_postofficebox]                  NVARCHAR (20)    NULL,
    [sic]                                     NVARCHAR (20)    NULL,
    [statecode]                               INT              NULL,
    [statecode_displayname]                   NVARCHAR (255)   NULL,
    [SCRIBE_ID]                               BIGINT           IDENTITY (1, 1) NOT NULL,
    [SCRIBE_CREATEDON]                        DATETIME         NOT NULL,
    [SCRIBE_MODIFIEDON]                       DATETIME         NOT NULL,
    [SCRIBE_DELETEDON]                        DATETIME         NULL,
    CONSTRAINT [PK_lead] PRIMARY KEY CLUSTERED ([SCRIBE_ID] ASC)
);

