CREATE TABLE [dbo].[opportunityproduct] (
    [productid]                               UNIQUEIDENTIFIER NULL,
    [entityimage_timestamp]                   BIGINT           NULL,
    [createdon]                               DATETIME         NULL,
    [modifiedonbehalfbyyominame]              NVARCHAR (4000)  NULL,
    [manualdiscountamount]                    DECIMAL (17, 2)  NULL,
    [modifiedbyyominame]                      NVARCHAR (4000)  NULL,
    [opportunityidname]                       NVARCHAR (4000)  NULL,
    [owneridtype]                             NVARCHAR (255)   NULL,
    [productdescription]                      NVARCHAR (500)   NULL,
    [overriddencreatedon]                     DATETIME         NULL,
    [parentbundleid]                          UNIQUEIDENTIFIER NULL,
    [baseamount]                              DECIMAL (17, 2)  NULL,
    [modifiedonbehalfby]                      UNIQUEIDENTIFIER NULL,
    [exchangerate]                            DECIMAL (22, 10) NULL,
    [baseamount_base]                         DECIMAL (19, 4)  NULL,
    [priceperunit]                            DECIMAL (17, 2)  NULL,
    [timezoneruleversionnumber]               INT              NULL,
    [opportunityid]                           UNIQUEIDENTIFIER NULL,
    [owninguser]                              UNIQUEIDENTIFIER NULL,
    [versionnumber]                           BIGINT           NULL,
    [sequencenumber]                          INT              NULL,
    [priceperunit_base]                       DECIMAL (19, 4)  NULL,
    [uomidname]                               NVARCHAR (4000)  NULL,
    [tax_base]                                DECIMAL (19, 4)  NULL,
    [createdby]                               UNIQUEIDENTIFIER NULL,
    [utcconversiontimezonecode]               INT              NULL,
    [uomid]                                   UNIQUEIDENTIFIER NULL,
    [producttypecode]                         INT              NULL,
    [producttypecode_displayname]             NVARCHAR (255)   NULL,
    [ownerid]                                 UNIQUEIDENTIFIER NULL,
    [modifiedon]                              DATETIME         NULL,
    [importsequencenumber]                    INT              NULL,
    [isproductoverridden]                     TINYINT          NULL,
    [modifiedby]                              UNIQUEIDENTIFIER NULL,
    [manualdiscountamount_base]               DECIMAL (19, 4)  NULL,
    [description]                             NVARCHAR (MAX)   NULL,
    [entityimageid]                           UNIQUEIDENTIFIER NULL,
    [createdbyname]                           NVARCHAR (4000)  NULL,
    [ispriceoverridden]                       TINYINT          NULL,
    [modifiedonbehalfbyname]                  NVARCHAR (4000)  NULL,
    [opportunityproductid]                    UNIQUEIDENTIFIER NULL,
    [transactioncurrencyid]                   UNIQUEIDENTIFIER NULL,
    [createdonbehalfby]                       UNIQUEIDENTIFIER NULL,
    [pricingerrorcode]                        INT              NULL,
    [pricingerrorcode_displayname]            NVARCHAR (255)   NULL,
    [createdbyyominame]                       NVARCHAR (4000)  NULL,
    [volumediscountamount_base]               DECIMAL (19, 4)  NULL,
    [transactioncurrencyidname]               NVARCHAR (4000)  NULL,
    [createdonbehalfbyyominame]               NVARCHAR (4000)  NULL,
    [owningbusinessunit]                      UNIQUEIDENTIFIER NULL,
    [createdonbehalfbyname]                   NVARCHAR (4000)  NULL,
    [quantity]                                DECIMAL (17, 5)  NULL,
    [extendedamount_base]                     DECIMAL (19, 4)  NULL,
    [opportunitystatecode]                    INT              NULL,
    [opportunitystatecode_displayname]        NVARCHAR (255)   NULL,
    [propertyconfigurationstatus]             INT              NULL,
    [propertyconfigurationstatus_displayname] NVARCHAR (255)   NULL,
    [productidname]                           NVARCHAR (4000)  NULL,
    [extendedamount]                          DECIMAL (17, 2)  NULL,
    [modifiedbyname]                          NVARCHAR (4000)  NULL,
    [lineitemnumber]                          INT              NULL,
    [volumediscountamount]                    DECIMAL (17, 2)  NULL,
    [tax]                                     DECIMAL (17, 2)  NULL,
    [entityimage_url]                         NVARCHAR (4000)  NULL,
    [productassociationid]                    UNIQUEIDENTIFIER NULL,
    [SCRIBE_ID]                               BIGINT           IDENTITY (1, 1) NOT NULL,
    [SCRIBE_CREATEDON]                        DATETIME         NOT NULL,
    [SCRIBE_MODIFIEDON]                       DATETIME         NOT NULL,
    [SCRIBE_DELETEDON]                        DATETIME         NULL,
    CONSTRAINT [PK_opportunityproduct] PRIMARY KEY CLUSTERED ([SCRIBE_ID] ASC)
);

