CREATE TABLE [dbo].[product] (
    [iskit]                        TINYINT          NULL,
    [productid]                    UNIQUEIDENTIFIER NULL,
    [entityimage_timestamp]        BIGINT           NULL,
    [createdon]                    DATETIME         NULL,
    [standardcost_base]            DECIMAL (19, 4)  NULL,
    [createdbyname]                NVARCHAR (4000)  NULL,
    [parentproductidname]          NVARCHAR (4000)  NULL,
    [modifiedbyyominame]           NVARCHAR (4000)  NULL,
    [productstructure]             INT              NULL,
    [productstructure_displayname] NVARCHAR (255)   NULL,
    [modifiedbyname]               NVARCHAR (4000)  NULL,
    [defaultuomidname]             NVARCHAR (4000)  NULL,
    [validfromdate]                DATETIME         NULL,
    [price_base]                   DECIMAL (19, 4)  NULL,
    [currentcost]                  DECIMAL (15, 2)  NULL,
    [defaultuomscheduleidname]     NVARCHAR (4000)  NULL,
    [createdonbehalfbyyominame]    NVARCHAR (4000)  NULL,
    [modifiedonbehalfby]           UNIQUEIDENTIFIER NULL,
    [exchangerate]                 DECIMAL (22, 10) NULL,
    [overriddencreatedon]          DATETIME         NULL,
    [producturl]                   NVARCHAR (255)   NULL,
    [statecode]                    INT              NULL,
    [statecode_displayname]        NVARCHAR (255)   NULL,
    [price]                        DECIMAL (15, 2)  NULL,
    [defaultuomscheduleid]         UNIQUEIDENTIFIER NULL,
    [timezoneruleversionnumber]    INT              NULL,
    [size]                         NVARCHAR (200)   NULL,
    [pricelevelid]                 UNIQUEIDENTIFIER NULL,
    [versionnumber]                BIGINT           NULL,
    [traversedpath]                NVARCHAR (1250)  NULL,
    [createdonbehalfbyname]        NVARCHAR (4000)  NULL,
    [createdbyyominame]            NVARCHAR (4000)  NULL,
    [createdonbehalfby]            UNIQUEIDENTIFIER NULL,
    [utcconversiontimezonecode]    INT              NULL,
    [vendorname]                   NVARCHAR (100)   NULL,
    [producttypecode]              INT              NULL,
    [producttypecode_displayname]  NVARCHAR (255)   NULL,
    [vendorpartnumber]             NVARCHAR (100)   NULL,
    [modifiedon]                   DATETIME         NULL,
    [importsequencenumber]         INT              NULL,
    [processid]                    UNIQUEIDENTIFIER NULL,
    [description]                  NVARCHAR (MAX)   NULL,
    [parentproductid]              UNIQUEIDENTIFIER NULL,
    [modifiedonbehalfbyname]       NVARCHAR (4000)  NULL,
    [subjectid]                    UNIQUEIDENTIFIER NULL,
    [subjectidname]                NVARCHAR (4000)  NULL,
    [stageid]                      UNIQUEIDENTIFIER NULL,
    [defaultuomid]                 UNIQUEIDENTIFIER NULL,
    [stockvolume]                  DECIMAL (12, 2)  NULL,
    [quantitydecimal]              INT              NULL,
    [transactioncurrencyid]        UNIQUEIDENTIFIER NULL,
    [isstockitem]                  TINYINT          NULL,
    [quantityonhand]               DECIMAL (12, 2)  NULL,
    [createdby]                    UNIQUEIDENTIFIER NULL,
    [pricelevelidname]             NVARCHAR (4000)  NULL,
    [modifiedby]                   UNIQUEIDENTIFIER NULL,
    [transactioncurrencyidname]    NVARCHAR (4000)  NULL,
    [vendorid]                     NVARCHAR (100)   NULL,
    [currentcost_base]             DECIMAL (19, 4)  NULL,
    [hierarchypath]                NVARCHAR (450)   NULL,
    [suppliername]                 NVARCHAR (100)   NULL,
    [validtodate]                  DATETIME         NULL,
    [name]                         NVARCHAR (100)   NULL,
    [entityimage_url]              NVARCHAR (4000)  NULL,
    [stockweight]                  DECIMAL (12, 2)  NULL,
    [statuscode]                   INT              NULL,
    [statuscode_displayname]       NVARCHAR (255)   NULL,
    [modifiedonbehalfbyyominame]   NVARCHAR (4000)  NULL,
    [dmtimportstate]               INT              NULL,
    [organizationid]               UNIQUEIDENTIFIER NULL,
    [productnumber]                NVARCHAR (100)   NULL,
    [entityimageid]                UNIQUEIDENTIFIER NULL,
    [organizationidname]           NVARCHAR (4000)  NULL,
    [standardcost]                 DECIMAL (15, 2)  NULL,
    [SCRIBE_ID]                    BIGINT           IDENTITY (1, 1) NOT NULL,
    [SCRIBE_CREATEDON]             DATETIME         NOT NULL,
    [SCRIBE_MODIFIEDON]            DATETIME         NOT NULL,
    [SCRIBE_DELETEDON]             DATETIME         NULL,
    CONSTRAINT [PK_product] PRIMARY KEY CLUSTERED ([SCRIBE_ID] ASC)
);

