CREATE VIEW [Smgt].[DateView]
AS
  SELECT [date_key],
         [full_date] AS [Date],
         [day_of_week] AS [Day of the Week],
         [day_num_in_month] AS [Day Number of the Month],
		 [day_num_in_year] AS [Day Number of the Year],
         [day_name] AS [Day Name],
         [day_abbrev] AS [Day Abbreviated],
         [weekday_flag]  AS [Weekday Flag],
         [week_num_in_year] AS [Week Number in Year],
         [week_begin_date] AS [Week Begin Date],
         [week_begin_date_key],
         [month],
         [month_name] AS [Month Name],
         [month_abbrev],
         [quarter],
         [year],
         [yearmo],
         [fiscal_month] AS [Fiscal Month],
         [fiscal_quarter] AS [Fiscal Quarter],
         [fiscal_year] AS [Fiscal Year],
         [last_day_in_month_flag],
         [same_day_year_ago_date],
         [same_day_year_ago_key],
         [quarter_name],
         [fiscal_quarter_name] AS [Fiscal Quarter Name],
         [fiscalyearcompletename] AS [Fiscal Year Name],
         [fiscalquartercompletename] AS [Fiscal Quarter Full Name],
		 [FiscalMonthCompleteName] AS [Fiscal Month Full Name]
  FROM   [Smgt].[date]