CREATE TABLE [bm].[date](
	date_key               INT NOT NULL,
	full_date              DATE NOT NULL,
	day_of_week            TINYINT NOT NULL,
	day_num_in_month       TINYINT NOT NULL,
	day_name               CHAR(9) NOT NULL,
	day_abbrev             CHAR(3) NOT NULL,
	weekday_flag           CHAR(1) NOT NULL,
	week_num_in_year       TINYINT NOT NULL,
	week_begin_date        DATE NOT NULL,
	week_begin_date_key    INT NOT NULL,
	[month]                TINYINT NOT NULL,
	month_name             CHAR(9) NOT NULL,
	month_abbrev           CHAR(3) NOT NULL,
	[quarter]              TINYINT NOT NULL,
	[year]                 SMALLINT NOT NULL,
	yearmo                 INT NOT NULL,
	fiscal_month           TINYINT NOT NULL,
	fiscal_quarter         TINYINT NOT NULL,
	fiscal_year            SMALLINT NOT NULL,
	last_day_in_month_flag CHAR(1) NOT NULL,
	same_day_year_ago_date DATE NOT NULL,
	same_day_year_ago_key  INT NOT NULL,
	day_num_in_year       AS datepart(dayofyear, full_date),
	[quarter_name] AS Concat('Q', [quarter]),
	fiscal_quarter_name AS Concat('Q', fiscal_quarter),
	[FiscalQuarterCompleteName] AS Concat('FY', SUBSTRING(CONVERT(VARCHAR,[fiscal_year]),3,2)  ,' Q', [fiscal_quarter]),
	[FiscalYearCompleteName] AS Concat('FY', SUBSTRING(CONVERT(VARCHAR,[fiscal_year]),3,2)),
	[FiscalMonthCompleteName] AS Concat(month_abbrev, ' ' , SUBSTRING(CONVERT(VARCHAR,[fiscal_year]),3,2)),
    CONSTRAINT PK_Dim_Date PRIMARY KEY CLUSTERED (date_key) 
);
