CREATE TABLE [dbo].[account] (
    [emailaddress3]                            NVARCHAR (100)   NULL,
    [emailaddress2]                            NVARCHAR (100)   NULL,
    [emailaddress1]                            NVARCHAR (100)   NULL,
    [masteraccountidyominame]                  NVARCHAR (4000)  NULL,
    [address1_city]                            NVARCHAR (80)    NULL,
    [address1_line1]                           NVARCHAR (250)   NULL,
    [modifiedon]                               DATETIME         NULL,
    [aging90]                                  DECIMAL (17, 2)  NULL,
    [overriddencreatedon]                      DATETIME         NULL,
    [websiteurl]                               NVARCHAR (200)   NULL,
    [address1_longitude]                       FLOAT (53)       NULL,
    [donotpostalmail]                          TINYINT          NULL,
    [openrevenue]                              DECIMAL (17, 2)  NULL,
    [address1_addresstypecode]                 INT              NULL,
    [address1_addresstypecode_displayname]     NVARCHAR (255)   NULL,
    [entityimage_timestamp]                    BIGINT           NULL,
    [sharesoutstanding]                        INT              NULL,
    [donotsendmm]                              TINYINT          NULL,
    [primarycontactidname]                     NVARCHAR (4000)  NULL,
    [creditonhold]                             TINYINT          NULL,
    [transactioncurrencyidname]                NVARCHAR (4000)  NULL,
    [aging30]                                  DECIMAL (17, 2)  NULL,
    [donotbulkpostalmail]                      TINYINT          NULL,
    [preferredsystemuseridyominame]            NVARCHAR (4000)  NULL,
    [address1_shippingmethodcode]              INT              NULL,
    [address1_shippingmethodcode_displayname]  NVARCHAR (255)   NULL,
    [paymenttermscode]                         INT              NULL,
    [paymenttermscode_displayname]             NVARCHAR (255)   NULL,
    [opendeals_date]                           DATETIME         NULL,
    [originatingleadid]                        UNIQUEIDENTIFIER NULL,
    [masteraccountidname]                      NVARCHAR (4000)  NULL,
    [preferredsystemuseridname]                NVARCHAR (4000)  NULL,
    [accountcategorycode]                      INT              NULL,
    [accountcategorycode_displayname]          NVARCHAR (255)   NULL,
    [address2_stateorprovince]                 NVARCHAR (50)    NULL,
    [territoryid]                              UNIQUEIDENTIFIER NULL,
    [address2_country]                         NVARCHAR (80)    NULL,
    [address2_line2]                           NVARCHAR (250)   NULL,
    [aging60_base]                             DECIMAL (19, 4)  NULL,
    [address1_line3]                           NVARCHAR (250)   NULL,
    [address1_freighttermscode]                INT              NULL,
    [address1_freighttermscode_displayname]    NVARCHAR (255)   NULL,
    [creditlimit]                              DECIMAL (17, 2)  NULL,
    [openrevenue_base]                         DECIMAL (17, 2)  NULL,
    [parentaccountidname]                      NVARCHAR (4000)  NULL,
    [originatingleadidname]                    NVARCHAR (4000)  NULL,
    [address1_utcoffset]                       INT              NULL,
    [preferredappointmenttimecode]             INT              NULL,
    [preferredappointmenttimecode_displayname] NVARCHAR (255)   NULL,
    [numberofemployees]                        INT              NULL,
    [name]                                     NVARCHAR (160)   NULL,
    [accountclassificationcode]                INT              NULL,
    [accountclassificationcode_displayname]    NVARCHAR (255)   NULL,
    [revenue]                                  DECIMAL (17, 2)  NULL,
    [customertypecode]                         INT              NULL,
    [customertypecode_displayname]             NVARCHAR (255)   NULL,
    [exchangerate]                             DECIMAL (22, 10) NULL,
    [address2_county]                          NVARCHAR (50)    NULL,
    [isprivate]                                TINYINT          NULL,
    [primarycontactid]                         UNIQUEIDENTIFIER NULL,
    [telephone3]                               NVARCHAR (50)    NULL,
    [parentaccountid]                          UNIQUEIDENTIFIER NULL,
    [address2_city]                            NVARCHAR (80)    NULL,
    [statuscode]                               INT              NULL,
    [statuscode_displayname]                   NVARCHAR (255)   NULL,
    [address2_latitude]                        FLOAT (53)       NULL,
    [createdon]                                DATETIME         NULL,
    [donotbulkemail]                           TINYINT          NULL,
    [address2_line1]                           NVARCHAR (250)   NULL,
    [donotfax]                                 TINYINT          NULL,
    [marketcap]                                DECIMAL (17, 2)  NULL,
    [address1_composite]                       NVARCHAR (MAX)   NULL,
    [ownershipcode]                            INT              NULL,
    [ownershipcode_displayname]                NVARCHAR (255)   NULL,
    [opendeals_state]                          INT              NULL,
    [owningbusinessunit]                       UNIQUEIDENTIFIER NULL,
    [address2_postalcode]                      NVARCHAR (20)    NULL,
    [lastusedincampaign]                       DATETIME         NULL,
    [utcconversiontimezonecode]                INT              NULL,
    [owneridyominame]                          NVARCHAR (4000)  NULL,
    [entityimage_url]                          NVARCHAR (4000)  NULL,
    [address2_line3]                           NVARCHAR (250)   NULL,
    [description]                              NVARCHAR (MAX)   NULL,
    [modifiedby]                               UNIQUEIDENTIFIER NULL,
    [timezoneruleversionnumber]                INT              NULL,
    [address1_county]                          NVARCHAR (50)    NULL,
    [createdbyname]                            NVARCHAR (4000)  NULL,
    [modifiedonbehalfby]                       UNIQUEIDENTIFIER NULL,
    [donotemail]                               TINYINT          NULL,
    [territorycode]                            INT              NULL,
    [territorycode_displayname]                NVARCHAR (255)   NULL,
    [new_oldname]                              NVARCHAR (160)   NULL,
    [address2_postofficebox]                   NVARCHAR (20)    NULL,
    [address2_telephone1]                      NVARCHAR (50)    NULL,
    [address2_telephone2]                      NVARCHAR (50)    NULL,
    [address2_telephone3]                      NVARCHAR (50)    NULL,
    [originatingleadidyominame]                NVARCHAR (4000)  NULL,
    [address1_addressid]                       UNIQUEIDENTIFIER NULL,
    [traversedpath]                            NVARCHAR (1250)  NULL,
    [territoryidname]                          NVARCHAR (4000)  NULL,
    [creditlimit_base]                         DECIMAL (19, 4)  NULL,
    [yominame]                                 NVARCHAR (160)   NULL,
    [createdonbehalfbyname]                    NVARCHAR (4000)  NULL,
    [owninguser]                               UNIQUEIDENTIFIER NULL,
    [industrycode]                             INT              NULL,
    [industrycode_displayname]                 NVARCHAR (255)   NULL,
    [address2_name]                            NVARCHAR (200)   NULL,
    [openrevenue_state]                        INT              NULL,
    [owneridtype]                              NVARCHAR (255)   NULL,
    [entityimageid]                            UNIQUEIDENTIFIER NULL,
    [aging60]                                  DECIMAL (17, 2)  NULL,
    [businesstypecode]                         INT              NULL,
    [businesstypecode_displayname]             NVARCHAR (255)   NULL,
    [owneridname]                              NVARCHAR (4000)  NULL,
    [modifiedonbehalfbyname]                   NVARCHAR (4000)  NULL,
    [createdonbehalfbyyominame]                NVARCHAR (4000)  NULL,
    [address2_composite]                       NVARCHAR (MAX)   NULL,
    [shippingmethodcode]                       INT              NULL,
    [shippingmethodcode_displayname]           NVARCHAR (255)   NULL,
    [address1_country]                         NVARCHAR (80)    NULL,
    [owningteam]                               UNIQUEIDENTIFIER NULL,
    [address1_stateorprovince]                 NVARCHAR (50)    NULL,
    [preferredequipmentid]                     UNIQUEIDENTIFIER NULL,
    [processid]                                UNIQUEIDENTIFIER NULL,
    [createdonbehalfby]                        UNIQUEIDENTIFIER NULL,
    [transactioncurrencyid]                    UNIQUEIDENTIFIER NULL,
    [accountratingcode]                        INT              NULL,
    [accountratingcode_displayname]            NVARCHAR (255)   NULL,
    [address1_telephone1]                      NVARCHAR (50)    NULL,
    [address1_telephone2]                      NVARCHAR (50)    NULL,
    [address1_telephone3]                      NVARCHAR (50)    NULL,
    [address1_postofficebox]                   NVARCHAR (20)    NULL,
    [defaultpricelevelidname]                  NVARCHAR (4000)  NULL,
    [fax]                                      NVARCHAR (50)    NULL,
    [masterid]                                 UNIQUEIDENTIFIER NULL,
    [sic]                                      NVARCHAR (20)    NULL,
    [ownerid]                                  UNIQUEIDENTIFIER NULL,
    [address2_utcoffset]                       INT              NULL,
    [stageid]                                  UNIQUEIDENTIFIER NULL,
    [accountnumber]                            NVARCHAR (20)    NULL,
    [address2_fax]                             NVARCHAR (50)    NULL,
    [revenue_base]                             DECIMAL (19, 4)  NULL,
    [merged]                                   TINYINT          NULL,
    [address2_longitude]                       FLOAT (53)       NULL,
    [defaultpricelevelid]                      UNIQUEIDENTIFIER NULL,
    [preferredequipmentidname]                 NVARCHAR (4000)  NULL,
    [aging90_base]                             DECIMAL (19, 4)  NULL,
    [donotphone]                               TINYINT          NULL,
    [address1_primarycontactname]              NVARCHAR (100)   NULL,
    [modifiedbyyominame]                       NVARCHAR (4000)  NULL,
    [address1_line2]                           NVARCHAR (250)   NULL,
    [modifiedonbehalfbyyominame]               NVARCHAR (4000)  NULL,
    [createdby]                                UNIQUEIDENTIFIER NULL,
    [address2_addresstypecode]                 INT              NULL,
    [address2_addresstypecode_displayname]     NVARCHAR (255)   NULL,
    [openrevenue_date]                         DATETIME         NULL,
    [address2_upszone]                         NVARCHAR (4)     NULL,
    [marketcap_base]                           DECIMAL (19, 4)  NULL,
    [address1_postalcode]                      NVARCHAR (20)    NULL,
    [tickersymbol]                             NVARCHAR (10)    NULL,
    [customersizecode]                         INT              NULL,
    [customersizecode_displayname]             NVARCHAR (255)   NULL,
    [preferredserviceidname]                   NVARCHAR (4000)  NULL,
    [participatesinworkflow]                   TINYINT          NULL,
    [stockexchange]                            NVARCHAR (20)    NULL,
    [preferredserviceid]                       UNIQUEIDENTIFIER NULL,
    [preferredcontactmethodcode]               INT              NULL,
    [preferredcontactmethodcode_displayname]   NVARCHAR (255)   NULL,
    [importsequencenumber]                     INT              NULL,
    [telephone2]                               NVARCHAR (50)    NULL,
    [versionnumber]                            BIGINT           NULL,
    [preferredsystemuserid]                    UNIQUEIDENTIFIER NULL,
    [accountid]                                UNIQUEIDENTIFIER NULL,
    [telephone1]                               NVARCHAR (50)    NULL,
    [aging30_base]                             DECIMAL (19, 4)  NULL,
    [address1_name]                            NVARCHAR (200)   NULL,
    [address1_fax]                             NVARCHAR (50)    NULL,
    [address1_latitude]                        FLOAT (53)       NULL,
    [address2_shippingmethodcode]              INT              NULL,
    [address2_shippingmethodcode_displayname]  NVARCHAR (255)   NULL,
    [primarycontactidyominame]                 NVARCHAR (4000)  NULL,
    [preferredappointmentdaycode]              INT              NULL,
    [preferredappointmentdaycode_displayname]  NVARCHAR (255)   NULL,
    [modifiedbyname]                           NVARCHAR (4000)  NULL,
    [createdbyyominame]                        NVARCHAR (4000)  NULL,
    [address2_freighttermscode]                INT              NULL,
    [address2_freighttermscode_displayname]    NVARCHAR (255)   NULL,
    [address1_upszone]                         NVARCHAR (4)     NULL,
    [address2_addressid]                       UNIQUEIDENTIFIER NULL,
    [ftpsiteurl]                               NVARCHAR (200)   NULL,
    [parentaccountidyominame]                  NVARCHAR (4000)  NULL,
    [address2_primarycontactname]              NVARCHAR (100)   NULL,
    [opendeals]                                INT              NULL,
    [statecode]                                INT              NULL,
    [statecode_displayname]                    NVARCHAR (255)   NULL,
    [SCRIBE_ID]                                BIGINT           IDENTITY (1, 1) NOT NULL,
    [SCRIBE_CREATEDON]                         DATETIME         NOT NULL,
    [SCRIBE_MODIFIEDON]                        DATETIME         NOT NULL,
    [SCRIBE_DELETEDON]                         DATETIME         NULL,
    CONSTRAINT [PK_account] PRIMARY KEY CLUSTERED ([SCRIBE_ID] ASC)
);

