
CREATE TABLE [dbo].[Customer](
	[timestamp] [timestamp] NOT NULL,
	[No_] [nvarchar](20) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Search Name] [nvarchar](50) NOT NULL,
	[Name 2] [nvarchar](50) NOT NULL,
	[Address] [nvarchar](50) NOT NULL,
	[Address 2] [nvarchar](50) NOT NULL,
	[City] [nvarchar](30) NOT NULL,
	[Contact] [nvarchar](50) NOT NULL,
	[Phone No_] [nvarchar](30) NOT NULL,
	[Telex No_] [nvarchar](20) NOT NULL,
	[Document Sending Profile] [nvarchar](20) NOT NULL,
	[Our Account No_] [nvarchar](20) NOT NULL,
	[Territory Code] [nvarchar](10) NOT NULL,
	[Global Dimension 1 Code] [nvarchar](20) NOT NULL,
	[Global Dimension 2 Code] [nvarchar](20) NOT NULL,
	[Chain Name] [nvarchar](10) NOT NULL,
	[Budgeted Amount] [decimal](38, 20) NOT NULL,
	[Credit Limit (LCY)] [decimal](38, 20) NOT NULL,
	[Customer Posting Group] [nvarchar](10) NOT NULL,
	[Currency Code] [nvarchar](10) NOT NULL,
	[Customer Price Group] [nvarchar](10) NOT NULL,
	[Language Code] [nvarchar](10) NOT NULL,
	[Statistics Group] [int] NOT NULL,
	[Payment Terms Code] [nvarchar](10) NOT NULL,
	[Fin_ Charge Terms Code] [nvarchar](10) NOT NULL,
	[Salesperson Code] [nvarchar](10) NOT NULL,
	[Shipment Method Code] [nvarchar](10) NOT NULL,
	[Shipping Agent Code] [nvarchar](10) NOT NULL,
	[Place of Export] [nvarchar](20) NOT NULL,
	[Invoice Disc_ Code] [nvarchar](20) NOT NULL,
	[Customer Disc_ Group] [nvarchar](20) NOT NULL,
	[Country_Region Code] [nvarchar](10) NOT NULL,
	[Collection Method] [nvarchar](20) NOT NULL,
	[Amount] [decimal](38, 20) NOT NULL,
	[Blocked] [int] NOT NULL,
	[Invoice Copies] [int] NOT NULL,
	[Last Statement No_] [int] NOT NULL,
	[Print Statements] [tinyint] NOT NULL,
	[Bill-to Customer No_] [nvarchar](20) NOT NULL,
	[Priority] [int] NOT NULL,
	[Payment Method Code] [nvarchar](10) NOT NULL,
	[Last Date Modified] [datetime] NOT NULL,
	[Application Method] [int] NOT NULL,
	[Prices Including VAT] [tinyint] NOT NULL,
	[Location Code] [nvarchar](10) NOT NULL,
	[Fax No_] [nvarchar](30) NOT NULL,
	[Telex Answer Back] [nvarchar](20) NOT NULL,
	[VAT Registration No_] [nvarchar](20) NOT NULL,
	[Combine Shipments] [tinyint] NOT NULL,
	[Gen_ Bus_ Posting Group] [nvarchar](10) NOT NULL,
	[Picture] [image] NULL,
	[GLN] [nvarchar](13) NOT NULL,
	[Post Code] [nvarchar](20) NOT NULL,
	[County] [nvarchar](30) NOT NULL,
	[E-Mail] [nvarchar](80) NOT NULL,
	[Home Page] [nvarchar](80) NOT NULL,
	[Reminder Terms Code] [nvarchar](10) NOT NULL,
	[No_ Series] [nvarchar](10) NOT NULL,
	[Tax Area Code] [nvarchar](20) NOT NULL,
	[Tax Liable] [tinyint] NOT NULL,
	[VAT Bus_ Posting Group] [nvarchar](10) NOT NULL,
	[Reserve] [int] NOT NULL,
	[Block Payment Tolerance] [tinyint] NOT NULL,
	[IC Partner Code] [nvarchar](20) NOT NULL,
	[Prepayment _] [decimal](38, 20) NOT NULL,
	[Partner Type] [int] NOT NULL,
	[Preferred Bank Account] [nvarchar](10) NOT NULL,
	[Cash Flow Payment Terms Code] [nvarchar](10) NOT NULL,
	[Primary Contact No_] [nvarchar](20) NOT NULL,
	[Responsibility Center] [nvarchar](10) NOT NULL,
	[Shipping Advice] [int] NOT NULL,
	[Shipping Time] [varchar](32) NOT NULL,
	[Shipping Agent Service Code] [nvarchar](10) NOT NULL,
	[Service Zone Code] [nvarchar](10) NOT NULL,
	[Allow Line Disc_] [tinyint] NOT NULL,
	[Base Calendar Code] [nvarchar](10) NOT NULL,
	[Copy Sell-to Addr_ to Qte From] [int] NOT NULL,
	[UPS Zone] [nvarchar](2) NOT NULL,
	[Tax Exemption No_] [nvarchar](30) NOT NULL,
	[Bank Communication] [int] NOT NULL,
	[Check Date Format] [int] NOT NULL,
	[Check Date Separator] [int] NOT NULL,
	[RFC No_] [nvarchar](13) NOT NULL,
	[CURP No_] [nvarchar](18) NOT NULL,
	[State Inscription] [nvarchar](30) NOT NULL,
	[Tax Identification Type] [int] NOT NULL,
 CONSTRAINT [CRONUS USA, Inc_$Customer$0] PRIMARY KEY CLUSTERED 
(
	[No_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

