CREATE TABLE [dbo].[Account](
	[Id] [nvarchar](18) NULL,
	[IsDeleted] [tinyint] NULL,
	[MasterRecordId] [nvarchar](18) NULL,
	[Name] [nvarchar](255) NULL,
	[Type] [nvarchar](40) NULL,
	[ParentId] [nvarchar](18) NULL,
	[BillingStreet] [nvarchar](255) NULL,
	[BillingCity] [nvarchar](40) NULL,
	[BillingState] [nvarchar](80) NULL,
	[BillingPostalCode] [nvarchar](20) NULL,
	[BillingCountry] [nvarchar](80) NULL,
	[BillingLatitude] [float] NULL,
	[BillingLongitude] [float] NULL,
	[ShippingStreet] [nvarchar](255) NULL,
	[ShippingCity] [nvarchar](40) NULL,
	[ShippingState] [nvarchar](80) NULL,
	[ShippingPostalCode] [nvarchar](20) NULL,
	[ShippingCountry] [nvarchar](80) NULL,
	[ShippingLatitude] [float] NULL,
	[ShippingLongitude] [float] NULL,
	[Phone] [nvarchar](40) NULL,
	[Fax] [nvarchar](40) NULL,
	[AccountNumber] [nvarchar](40) NULL,
	[Website] [nvarchar](255) NULL,
	[PhotoUrl] [nvarchar](255) NULL,
	[Sic] [nvarchar](20) NULL,
	[Industry] [nvarchar](40) NULL,
	[AnnualRevenue] [float] NULL,
	[NumberOfEmployees] [int] NULL,
	[Ownership] [nvarchar](40) NULL,
	[TickerSymbol] [nvarchar](20) NULL,
	[Description] [nvarchar](max) NULL,
	[Rating] [nvarchar](40) NULL,
	[Site] [nvarchar](80) NULL,
	[OwnerId] [nvarchar](18) NULL,
	[CreatedDate] [datetime] NULL,
	[CreatedById] [nvarchar](18) NULL,
	[LastModifiedDate] [datetime] NULL,
	[LastModifiedById] [nvarchar](18) NULL,
	[SystemModstamp] [datetime] NULL,
	[LastActivityDate] [datetime] NULL,
	[LastViewedDate] [datetime] NULL,
	[LastReferencedDate] [datetime] NULL,
	[Jigsaw] [nvarchar](20) NULL,
	[JigsawCompanyId] [nvarchar](20) NULL,
	[CleanStatus] [nvarchar](40) NULL,
	[AccountSource] [nvarchar](40) NULL,
	[DunsNumber] [nvarchar](9) NULL,
	[Tradestyle] [nvarchar](255) NULL,
	[NaicsCode] [nvarchar](8) NULL,
	[NaicsDesc] [nvarchar](120) NULL,
	[YearStarted] [nvarchar](4) NULL,
	[SicDesc] [nvarchar](80) NULL,
	[DandbCompanyId] [nvarchar](18) NULL,
	[CustomerPriority__c] [nvarchar](255) NULL,
	[SLA__c] [nvarchar](255) NULL,
	[Active__c] [nvarchar](255) NULL,
	[NumberofLocations__c] [float] NULL,
	[UpsellOpportunity__c] [nvarchar](255) NULL,
	[SLASerialNumber__c] [nvarchar](10) NULL,
	[SLAExpirationDate__c] [datetime] NULL,
	[Import2_Id__c] [nvarchar](255) NULL,
	[Account_Parent_Import2_Id__c] [nvarchar](255) NULL,
	[SCRIBE_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SCRIBE_CREATEDON] [datetime] NOT NULL,
	[SCRIBE_MODIFIEDON] [datetime] NOT NULL,
	[SCRIBE_DELETEDON] [datetime] NULL,
 CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED 
(
	[SCRIBE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

